sudo: false
dist: xenial
cache:
  directories:
    - $HOME/.cache/pip
language: python
python:
  - "3.5"
env:
  - DJANGO=django~=2.0
  - DJANGO=django~=2.1
  - DJANGO=django~=2.2
install:
  - pip install -U pip pytest>=3.0.0
  - "pip install $DJANGO -e .[dev]"
script:
  - flake8 safespace
  - py.test -vvv --cov .
after_success:
  - bash <(curl -s https://codecov.io/bash)
