sudo: false
cache:
  directories:
    - $HOME/.cache/pip
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO=django~=1.8.0
  - DJANGO=django~=1.9.0
  - DJANGO=django~=1.10.0
install:
  - pip install -U pip pytest>=3.0.0
  - "pip install $DJANGO -e .[dev]"
script:
  - flake8 safespace
  - py.test -vvv --cov .
after_success:
  - bash <(curl -s https://codecov.io/bash)
