name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - python-version: '3.6'
            DJANGO: Django~=2.2.0
          - python-version: '3.6'
            DJANGO: Django~=3.0.0
          - python-version: '3.6'
            DJANGO: Django~=3.1.0
          - python-version: '3.8'
            DJANGO: Django~=4.0.0
    steps:
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - uses: actions/checkout@v2
      - run: pip install -U pip
      - run: 'pip install $DJANGO -e .[dev]'
        env:
          DJANGO: '${{ matrix.DJANGO }}'
      - run: flake8 safespace
      - run: py.test -vvv --cov .
      - uses: codecov/codecov-action@v2
